name: Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checking out 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Make
        run: npm run make

      - name: Test
        run: npm test

