name: Build Site

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: npm install
      run: |
        cd ./site
        npm install

    - name: Build
      run: |
        cd ./site
        npm run build

    - name: Deploy static files to another repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'site/public'
        destination-github-username: 'audiovideomerger'
        destination-repository-name: 'audiovideomerger.github.io'
        user-email: kasper.koman+audiovideomerger@gmail.com