name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  build-x64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checking out 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci --arch=x64

      - name: Lint
        run: npm run lint

      - name: Make
        run: npm run make -- --arch=x64

      - name: Test
        run: npm test

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: zip-x64
          path: ./out/make/zip/darwin/x64/*.zip

  build-arm64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checking out 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci --arch=arm64

      - name: Lint
        run: npm run lint

      - name: Make
        run: npm run make -- --arch=arm64

      - name: Test
        run: npm test

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: zip-arm64
          path: ./out/make/zip/darwin/arm64/*.zip
