name: Build Site

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: npm install
      run: |
        cd ./site
        npm install

    - name: Build
      run: |
        cd ./site
        npm run build

    - name: Deploy to local repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/public

    - name: Deploy to remote repo
      uses: johno/actions-push-subdirectories@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./site/public audiovideomerger audiovideomerger.github.io