name: Build Site

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      
jobs:
  build-site:
    
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: npm install
      run: |
        cd ./site
        npm install

    - name: Build
      run: |
        cd ./site
        npm run build

    - name: Deploy static files to another repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'site/public'
        destination-github-username: 'audiovideomerger'
        destination-repository-name: 'audiovideomerger.github.io'
        user-email: kasper.koman+audiovideomerger@gmail.com
